init: git config --global core.autocrlf input

shallow_clone: true

version: '1.0.{build}'

skip_tags: true

environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '0'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script: npm test

build: off

cache: node_modules -> package.json
