sections:
  - title: "Overview"
    icon:  "cog"
    href:  "/server-info.html"
  - title: "Sync Options"
    icon:  "sync"
    href:  "/sync-options.html"
  - title: "History"
    icon:  "list2"
    href:  "/history.html"
  - title: "Plugins"
    icon:  "plug"
    href:  "/plugins.html"
  - title: "Remote Debug"
    icon:  "bug"
    href:  "/remote-debug.html"
  - title: "Network Throttle"
    icon:  "time"
    href:  "/network-throttle.html"
  - title: "Help / About"
    icon:  "help"
    href:  "/help.html"

links:
  github:  "https://github.com/BrowserSync/browser-sync/"
  issues:  "https://github.com/BrowserSync/browser-sync/issues"
  twitter: "https://twitter.com/browsersync"
  home:    "https://browsersync.io"
  stackoverflow:  "https://stackoverflow.com/questions/tagged/browser-sync"
  snippetOptions: "https://www.browsersync.io/docs/options/#option-snippetOptions"
  contributing: "https://github.com/shakyShane/browser-sync/blob/master/CONTRIBUTING.md"
  options: "https://www.browsersync.io/docs/options"
  jh: "https://wearejh.com"

project:
  name: "Browsersync.io"
